# Example Configuration File for GoSight Agent
#
# This file provides an example configuration for the GoSight Agent. Below is a detailed explanation of each field:
#
# agent:
#   - server_url: The URL of the GoSight server to which the agent sends data. Format: domain/ip:port.
#   - host: The hostname of the machine where the agent is running. This is used for identification.
#   - log_collection: Configuration for log collection.
#       - sources: List of log sources to collect from (e.g., journald, eventviewer).
#       - batch_size: Number of log entries to send in a single payload.
#       - message_max: Maximum size of log messages before truncation.
#       - buffer_size: Maximum size of the buffer before sending logs.
#       - workers: Number of worker threads for log collection.
#       - interval: Time interval for log collection.
#       - eventviewer: Configuration specific to Windows Event Viewer.
#           - collect_all: Whether to collect logs from all available channels.
#           - channels: List of specific channels to collect logs from (if collect_all is false).
#           - exclude_channels: List of channels to exclude from log collection.
#   - metric_collection: Configuration for metric collection.
#       - workers: Number of worker threads for metric collection.
#       - interval: Time interval for metric collection.
#       - sources: List of metrics to collect (e.g., cpu, mem, disk, net).
#   - process_collection: Configuration for process information collection.
#       - workers: Number of worker threads for process collection.
#       - interval: Time interval for process collection.
#   - environment: The environment in which the agent is running (e.g., dev, prod).
#
# logs:
#   - error_log_file: Path to the error log file.
#   - app_log_file: Path to the application log file.
#   - access_log_file: Path to the access log file.
#   - debug_log_file: Path to the debug log file.
#   - log_level: Logging level (e.g., debug, info).
#
# tls:
#   - ca_file: Path to the Certificate Authority (CA) file.
#   - cert_file: Path to the client certificate file (required for mutual TLS).
#   - key_file: Path to the client key file (required for mutual TLS).
#
# podman:
#   - enabled: Whether the Podman collector is enabled.
#   - socket: Path to the Podman socket file.
#
# docker:
#   - enabled: Whether the Docker collector is enabled.
#   - socket: Path to the Docker socket file.

agent:
  server_url: "localhost:4317"    # domain/ip:port
  host: "dev-machine-01"    # Hostname of agent machine
  log_collection:
      sources:
        - journald
        - eventviewer
          #- security
      batch_size:  50     # Number of log entries to send in a payload
      message_max: 10000   # Max size of messages before truncating (like in journald)
      buffer_size: 500 # Max size of the buffer before sending
      workers: 2
      interval: 30s
      # Windows Event Log configuration
      eventviewer:
        # Set to true to collect from all available channels
        collect_all: false
        # List of channels to collect from (if collect_all is false)
        channels:
          # System logs
          - System
          - Security
          - Application
          # Windows logs
          - "Microsoft-Windows-Windows Defender/Operational"
          - "Microsoft-Windows-WindowsUpdateClient/Operational"
          - "Microsoft-Windows-PowerShell/Operational"
          - "Microsoft-Windows-Sysmon/Operational"
          - "Microsoft-Windows-TaskScheduler/Operational"
          - "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational"
          - "Microsoft-Windows-Security-Auditing/Operational"
          # Application logs
          - "Microsoft-Windows-PrintService/Operational"
          - "Microsoft-Windows-DNS-Client/Operational"
          - "Microsoft-Windows-DHCP-Client/Operational"
          # Service logs
          - "Microsoft-Windows-NetworkProfile/Operational"
          - "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational"
          - "Microsoft-Windows-BitLocker/BitLocker Management"
          - "Microsoft-Windows-CodeIntegrity/Operational"
          # Hardware logs
          - "Microsoft-Windows-Storage-Storport/Operational"
          - "Microsoft-Windows-Kernel-Boot/Operational"
          - "Microsoft-Windows-Kernel-PnP/Configuration"
          # Security logs
          - "Microsoft-Windows-AppLocker/EXE and DLL"
          - "Microsoft-Windows-AppLocker/MSI and Script"
          - "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall"
          # Active Directory logs (if applicable)
          - "Directory Service"
          - "DFS Replication"
          - "DNS Server"
        # Channels to explicitly exclude (applies even if collect_all is true)
        exclude_channels:
          - "Microsoft-Windows-Diagnosis-*"
          - "Microsoft-Windows-DeviceSync*"
          - "Microsoft-Windows-Containers*"
          - "Microsoft-Windows-HelloForBusiness*"
          - "Microsoft-Windows-Help*"
          - "Microsoft-Windows-Audio*"
          - "Microsoft-Windows-International*"
          - "Microsoft-Windows-UserPnp*"
          - "Microsoft-Windows-Shell-Core*"
          - "Microsoft-Windows-Mobile*"
  metric_collection:
    workers: 2
    interval: 2s
    sources:
      - cpu
      - mem
      - host
      - disk
      - net
      - podman
  process_collection:
      workers: 2
      interval: 2s

  environment: "dev" # (dev/prod)

# Log Config
logs:
  error_log_file: "../logs/error_agent.log"
  app_log_file: "../logs/app_agent.log"
  access_log_file: "../logs/access_agent.log"
  debug_log_file: "../logs/debug_agent.log"
  log_level: "debug"            # Or "info", etc.

# TLS Config
tls:
  ca_file: "../certs/ca.crt"
  cert_file: "../certs/client.crt"         # (only needed if doing mTLS)
  key_file: "../certs/client.key"          # (only needed if doing mTLS)

# Podman collector config
podman:
  enabled: false
  socket: "/run/user/1000/podman/podman.sock"

docker:
  enabled: true
  socket: "/var/run/docker.sock"
